package View;

public enum LangStringID {
    MEM_MAIN_MENU,
    MEM_NAME,
    MEM_PERSNO,
    ADD_MEM,
    RETRIEVE_MEM,
    MEMBERUNIQID,
    CHANGE_CURRENT_LANGUAGE,
    UPDATE_MEM,
    REMOVE_MEM,
    ADD_BOAT,
    UPDATE_BOAT_INFO,
    DELETE_BOAT,
    VERBOSE_LIST,
    SAVE_AND_EXIT_,
    NAME,
    PERSONAL_NUMBER,
    NUMBER_OF_BOATS,
    UNIQUE_ID,
    REMOVED,
    DISPLAY_MEMBERS,

    COMPACT_LIST;

}
